module.exports = {
  templateDir: './template',
  files: [
    '.env',
    '.eslintrc',
    '.lintstagedrc',
    '.nvmrc',
    '.prettierrc',
    '.storybook',
    '.stylelintrc',
    '.husky',
    'babel.config.rollup.js',
    'docs',
    'jsconfig.json',
    'netlify.toml',
    'README.md',
    'rollup.config.js',
    'public',
    'prepare.js',
    'src',
  ],
};
